[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = ".netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "max-age=0, s-maxage=60"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 